Add CONTRIBUTING.md and document auto-reload
ditrit/leto-modelizer-plugin-template pull request #6
Opened 2023-05-17 13:38 UTC by viennem

2023-05-22 11:59 UTC, Zorin95670 requested changes

2023-05-22 11:59 UTC, Zorin95670 commented on CONTRIBUTING.md
> +1. Make sure you cloned the [leto-modelizer](https://github.com/ditrit/leto-modelizer) and your plugin's repos.
repository

2023-05-22 11:59 UTC, Zorin95670 commented on CONTRIBUTING.md
> +4. In `leto-modelizer`, run `npm run dev`.
Miss the edition of `package.json` with :
```
"exports": {
    ".": {
      "development": "./src",
      "default": "./dist/my-plugin.js"
    }
  },
```

2023-05-22 12:23 UTC, justinehell requested changes

2023-05-22 12:23 UTC, justinehell commented on CONTRIBUTING.md
> +The default branch is main. Direct commit on it is forbidden. The only way to update the application is through pull request.
The default branch is `main`.

2023-05-22 12:24 UTC, justinehell commented on CONTRIBUTING.md
> +1. Make sure you cloned the [leto-modelizer](https://github.com/ditrit/leto-modelizer) and your plugin's repos.
and your plugin's repositories.

2023-05-22 12:53 UTC, k-y0u requested changes

2023-05-22 12:53 UTC, k-y0u commented on CONTRIBUTING.md
> +When you are working on your plugin, you can choose to write your unit tests first to test your code (test-driven development).
When you are working on your plugin, you can start by writing your unit tests (TDD: test-driven development).

2023-05-22 12:53 UTC, k-y0u commented on CONTRIBUTING.md
> +- Once the pull request validated and merged, tag the `main` branch with `vX.Y.Z`
missing dot

2023-05-22 12:53 UTC, k-y0u commented on CONTRIBUTING.md
> +- After the tag is pushed, make the release on the tag in GitHub
missing dot

2023-05-22 12:53 UTC, k-y0u commented on CONTRIBUTING.md
> +The default branch is main. Direct commit on it is forbidden. The only way to update the application is through pull request.
The only way to update the `main` branch is through pull request.

2023-05-22 13:28 UTC, viennem commented on CONTRIBUTING.md
> +1. Make sure you cloned the [leto-modelizer](https://github.com/ditrit/leto-modelizer) and your plugin's repos.
fixed

2023-05-22 13:29 UTC, viennem commented on CONTRIBUTING.md
> +The default branch is main. Direct commit on it is forbidden. The only way to update the application is through pull request.
fixed

2023-05-22 13:29 UTC, viennem commented on CONTRIBUTING.md
> +When you are working on your plugin, you can choose to write your unit tests first to test your code (test-driven development).
fixed

2023-05-22 13:30 UTC, viennem commented on CONTRIBUTING.md
> +- Once the pull request validated and merged, tag the `main` branch with `vX.Y.Z`
fixed

2023-05-22 13:30 UTC, viennem commented on CONTRIBUTING.md
> +- After the tag is pushed, make the release on the tag in GitHub
fixed

2023-05-22 13:30 UTC, viennem commented on CONTRIBUTING.md
> +The default branch is main. Direct commit on it is forbidden. The only way to update the application is through pull request.
fixed

2023-05-22 13:56 UTC, viennem commented on CONTRIBUTING.md
> +   * You also need to install the dependencies of each cloned repository (by running `cd <repository_path>` and then `npm install`).
Note: I added this line since the last review.

2023-05-24 08:01 UTC, Zorin95670 commented on CONTRIBUTING.md
> +4. In `leto-modelizer`, run `npm run dev`.
or update the `package.json` with this modification

2023-05-26 13:18 UTC, Zorin95670 commented on CONTRIBUTING.md
> +4. In `leto-modelizer`, run `npm run dev`.
See with @viennem, not to be done.

2023-05-26 13:19 UTC, Zorin95670 commented on CONTRIBUTING.md
> +# Contributing
Bad branch name, according to the `Contributing.md` :/

2023-05-31 15:24 UTC, closed without merging